# Generated by Django 5.2.6 on 2025-09-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='manual_annual_leave_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override annual leave balance (leave blank for automatic calculation)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='probation_end_date',
            field=models.DateField(blank=True, help_text='Date when employee becomes eligible for leave (auto-calculated as 6 months from hire date if not specified)', null=True),
        ),
    ]
